CREATE TABLE IF NOT EXISTS USERS (
	user_id SERIAL PRIMARY KEY,
	user_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS OWNER_USER (
	owner_id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES USERS(user_id),
	maintenance_paid BOOLEAN,
	password_string VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ADMIN_USER (
	admin_id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES USERS(user_id),
	password_string VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SITE (
	site_number SERIAL PRIMARY KEY,
	ownership_status BOOLEAN,
	length_in_feet INTEGER NOT NULL,
	breadth_in_feet INTEGER NOT NULL,
	owner_id INTEGER REFERENCES OWNER_USER(owner_id)
);


CREATE TABLE IF NOT EXISTS OCCUPIED_SITE (
	occupied_site_number SERIAL PRIMARY KEY,
	site_number INTEGER REFERENCES SITE(site_number),	
	occupied_site_type VARCHAR(50) NOT NULL,
	owner_id INTEGER REFERENCES OWNER_USER(owner_id)
);

CREATE TABLE IF NOT EXISTS MAINTENANCE (
	maintenance_id SERIAL PRIMARY KEY,
	site_number INTEGER REFERENCES SITE(site_number),
	maintenance_amount BIGINT,
	maintenance_month VARCHAR(3)
);

SELECT * FROM USERS
SELECT * FROM ADMIN_USER
SELECT * FROM OWNER_USER
SELECT * FROM SITE
SELECT * FROM OCCUPIED_SITE
SELECT * FROM MAINTENANCE

DROP TABLE IF EXISTS MAINTENANCE CASCADE;
DROP TABLE IF EXISTS OCCUPIED_SITE CASCADE;
DROP TABLE IF EXISTS SITE CASCADE;
DROP TABLE IF EXISTS OWNER_USER CASCADE;
DROP TABLE IF EXISTS ADMIN_USER CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;



