CREATE TABLE IF NOT EXISTS USERS (
	user_id SERIAL PRIMARY KEY,
	user_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS OWNER_USER (
	owner_id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES USERS(user_id),
	maintenance_paid BOOLEAN,
	password_string VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ADMIN_USER (
	admin_id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES USERS(user_id),
	password_string VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SITE (
	site_number SERIAL PRIMARY KEY,
	ownership_status BOOLEAN,
	length_in_feet INTEGER NOT NULL,
	breadth_in_feet INTEGER NOT NULL,
	owner_id INTEGER REFERENCES OWNER_USER(owner_id),
	house_type VARCHAR(25)
);


CREATE TABLE IF NOT EXISTS MAINTENANCE (
	maintenance_id SERIAL PRIMARY KEY,
	site_number INTEGER REFERENCES SITE(site_number),
	maintenance_amount BIGINT,
	maintenance_month VARCHAR(3),
	payment_made BOOLEAN,
	payment_date DATE
);

CREATE TABLE IF NOT EXISTS MAINTENANCE_PAYMENT_REQUEST (
	maintenance_payment_request_id SERIAL PRIMARY KEY,
	site_number INTEGER REFERENCES SITE(site_number),
	maintenance_amount BIGINT,
	maintenance_month VARCHAR(3),
	payment_request_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	payment_date TIMESTAMP
);

SELECT * FROM USERS
SELECT * FROM ADMIN_USER
SELECT * FROM OWNER_USER
SELECT * FROM SITE
SELECT * FROM MAINTENANCE


UPDATE SITE SET owner_id = 1, ownership_status=? WHERE site_number=?

DROP TABLE IF EXISTS MAINTENANCE CASCADE;
DROP TABLE IF EXISTS MAINTENANCE_PAYMENT_REQUEST CASCADE;
DROP TABLE IF EXISTS OCCUPIED_SITE CASCADE;
DROP TABLE IF EXISTS SITE CASCADE;
DROP TABLE IF EXISTS OWNER_USER CASCADE;
DROP TABLE IF EXISTS ADMIN_USER CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

SELECT * FROM MAINTENANCE_PAYMENT_REQUEST



